spring:
  application:
    name: cards
  datasource:
    url: jdbc:h2:mem:cardsdbqa
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
server:
  port: 8081
