spring:
  application:
    name: accounts
  config:
    import: optional:configserver:http://localhost:8089/
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      enabled: true
      show-details: always
    info:
      enabled: true